<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>AccountRotation.App.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AccountRotation.App/AccountRotation.App.csproj" />
    <ProjectReference Include="../../src/AccountRotation.Core/AccountRotation.Core.csproj" />
  </ItemGroup>

</Project>
